# Generated by Django 3.0.3 on 2020-02-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first', models.CharField(max_length=200)),
                ('contact_last', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('number_of_awards', models.IntegerField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_number', models.IntegerField()),
                ('award_name', models.CharField(max_length=200000)),
                ('award_description', models.CharField(max_length=200000)),
                ('award_winner', models.CharField(max_length=2000)),
                ('award_comments', models.CharField(max_length=200000)),
                ('award_assets', models.FileField(upload_to='')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
