# Generated by Django 3.0.3 on 2020-02-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='client_name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='project_name',
            new_name='project',
        ),
    ]
