# Generated by Django 3.0.3 on 2020-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200228_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='award_assets',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
