# Generated by Django 3.0.3 on 2020-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200228_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='partner_logo',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
