# Generated by Django 3.0.3 on 2020-05-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200521_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('on_drive', models.BooleanField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Award')),
            ],
        ),
    ]
