# Generated by Django 3.0.3 on 2020-05-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project/%Y/%m/%d'),
        ),
    ]
