# Generated by Django 3.0.3 on 2020-05-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Award'),
        ),
        migrations.AlterField(
            model_name='file',
            name='on_drive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
