# Generated by Django 3.0.3 on 2020-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200303_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='session_hash',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='stage',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='attendees',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='exhibitors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='feature_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='feature_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='feature_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='theme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
