# Generated by Django 3.0.3 on 2020-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200525_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage='project/%Y/%m/%d', upload_to='project/%Y/%m/%d'),
        ),
    ]
