# Generated by Django 3.0.3 on 2020-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200310_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='assets',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='guests',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
