# Generated by Django 3.0.3 on 2020-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200310_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='draft',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='final_draft',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='script',
            field=models.URLField(null=True),
        ),
    ]
