# Generated by Django 3.0.3 on 2020-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200528_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
