# Generated by Django 3.0.3 on 2020-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200814_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
