# Generated by Django 3.0.3 on 2020-03-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200311_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='award_assets',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='draft',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='final_draft',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='script',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
