# Generated by Django 3.0.3 on 2020-08-28 19:02

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_awards_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='edit_comments',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
