# Generated by Django 3.0.3 on 2020-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200311_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
