# Generated by Django 3.0.3 on 2020-09-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200828_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
