# Generated by Django 3.0.3 on 2020-04-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200313_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Client Message', max_length=2000)),
                ('date', models.DateField(blank=True, null=True)),
                ('draft_script', models.URLField(blank=True, null=True)),
                ('script', models.URLField(blank=True, null=True)),
                ('assets', models.URLField(blank=True, null=True)),
                ('draft', models.URLField(blank=True, null=True)),
                ('final', models.URLField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
            ],
        ),
    ]
