# Generated by Django 3.0.3 on 2020-05-04 16:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200504_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
