# Generated by Django 3.0.3 on 2020-05-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200504_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='notes',
        ),
    ]
