# Generated by Django 3.0.3 on 2020-05-04 17:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_message_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
