# Generated by Django 3.0.3 on 2020-05-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_message_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='promotion',
            name='assets',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='feature_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='feature_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='guests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
