# Generated by Django 3.0.3 on 2020-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20200504_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Company',
        ),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
