# Generated by Django 3.0.3 on 2020-05-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200504_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
