# Generated by Django 3.0.3 on 2020-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_role',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
