# Generated by Django 3.0.3 on 2020-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20200507_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_project',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
