# Generated by Django 3.0.3 on 2020-05-13 20:12

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=200)),
                ('map_data', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='process_comment',
            field=models.CharField(choices=[('Script Rough Draft', 'rough_script'), ('Script Final Draft', 'final_script'), ('Video Rough Draft', 'video_rough'), ('Video Final Draft', 'final_video')], max_length=200, null=True),
        ),
    ]
